# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop

pool:
  name: "anas-agent"

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'pass project service'
    repository: 'passprojectcr'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
