# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop

pool:
  name: "anas-agent"


steps:
- task: Docker@2
  inputs:
    containerRegistry: 'pass project service'
    repository: 'passprojectcr'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'paas aks service'
    command: 'apply'
    useConfigurationFile: true
    configuration: 'deploy.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'Azure for Students(d3ea73b3-b9b0-4712-b718-a44a57a683d0)'
    azureContainerRegistry: 'passprojectcr.azurecr.io'
    secretName: 'reactauth'
